Enum protocol {
  local
  activitypub
  nostr
}

Table users {
  id varchar(255) [pk]
  username varchar(255)
  protocol protocol [not null]
  hashed_password varchar(255) [not null, default: ""]
  display_name varchar(255)
  profile text
  icon varchar(255)
  created_at timestamp [default: "CURRENT_TIMESTAMP"]
  updated_at timestamp [default: "CURRENT_TIMESTAMP"]
}

Table ap_user_identifiers {
  user_id varchar(255) [pk, ref: - users.id]
  local_username varchar(255) [not null]
  host varchar(255) [not null]
  public_key text [not null]
  private_key text
  created_at timestamp [default: "CURRENT_TIMESTAMP"]
  updated_at timestamp [default: "CURRENT_TIMESTAMP"]
}

Table nostr_user_identifiers {
  user_id varchar(255) [pk, ref: - users.id]
  public_key text [not null]
  private_key text
  created_at timestamp [default: "CURRENT_TIMESTAMP"]
  updated_at timestamp [default: "CURRENT_TIMESTAMP"]
}

Table follows {
  id varchar(255) [unique]
  follower_id varchar(255) [pk, ref: > users.id]
  followee_id varchar(255) [pk, ref: > users.id]
  is_accepted boolean [not null, default: false]
  created_at timestamp [default: "CURRENT_TIMESTAMP"]
  updated_at timestamp [default: "CURRENT_TIMESTAMP"]
}

Table posts {
  id varchar(255) [pk]
  user_id varchar(255) [ref: > users.id]
  content text [not null]
  created_at timestamp [default: "CURRENT_TIMESTAMP"]
  updated_at timestamp [default: "CURRENT_TIMESTAMP"]
}

Table nostr_relays {
  id varchar(255) [pk]
  url varchar(255) [not null, unique]
  is_enable boolean [not null, default: true]
  created_at timestamp [default: "CURRENT_TIMESTAMP"]
  updated_at timestamp [default: "CURRENT_TIMESTAMP"]
}
