version: 2
updates:
  # api (go)
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    #   - "auto-update"

  # frontend (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    #   - "auto-update"
