services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${API_PORT}
      - LOG_LEVEL=${API_LOG_LEVEL}
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    depends_on:
      - db
      - minio
    volumes:
      - ./api:/opt/app
    
  db:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${TIMEZONE}
      - PGTZ=${TIMEZONE}
    volumes:
      - db-data:/var/lib/postgresql/data

  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "${REVERSE_PROXY_PORT}:443"
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - api
    network_mode: host

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - "127.0.0.1:${MINIO_PORT}:9000"
      - "127.0.0.1:9001:9001" # minio console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
        cp -r /policies/* /data/.minio.sys/;
        cp -r /export/* /data/;
        /usr/bin/minio server /data --console-address :9001;
        "
    volumes:
      - minio-data:/data      
      - ./minio/export:/export
      - ./minio/policies:/policies
  
  backup:
    build:
      context: ./backup
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    depends_on:
      - db
      - minio

volumes:
  db-data:
  minio-data:
