services:
  api:
    build: ./api
    ports:
      - "1323:1323"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  reverse-proxy:
    image: nginx:1.27.0-alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - api
      - frontend
