services:
  api:
    build: ./api
    ports:
      - "127.0.0.1:1323:1323"

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api

  reverse-proxy:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - api
      - frontend
