services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${API_PORT}
      - LOG_LEVEL=${API_LOG_LEVEL}
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - db
    
  db:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data

  reverse-proxy:
    build: ./nginx
    ports:
      - "${REVERSE_PROXY_PORT}:443"
    depends_on:
      - api
    network_mode: host

volumes:
  dbdata:
