services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${API_PORT}
      - LOG_LEVEL=${API_LOG_LEVEL}
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
      - TZ=${TIMEZONE}
    depends_on:
      - db
      - minio
    volumes:
      - ./api:/opt/app
    
  db:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${TIMEZONE}
      - PGTZ=${TIMEZONE}
    volumes:
      - db-data:/var/lib/postgresql/data

  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "${REVERSE_PROXY_PORT}:443"
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - api
    network_mode: host

  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:${MINIO_PORT}:9000"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    command: server /var/lib/minio/data
    volumes:
      - minio-data:/var/lib/minio/data
    

volumes:
  db-data:
  minio-data:
