post:
  tags: 
    - config
  description: "Register a New Nostr Relay"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../../components/schemas/config.yaml#/nostr-relay'
  responses:
    '201':
      description: "Nostr Relay Registered"
      content:
        application/json:
          schema:
            type: object
    '400':
      description: "Invalid Request Body"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-400'
    '401':
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-401'
    '500':
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-500'

get:
  tags:
    - config
  description: "Get Nostr Relays List"
  responses:
    '200':
      description: "Nostr Relays List"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../../../components/schemas/config.yaml#/nostr-relay'
    '401':
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-401'
    '500':
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-500'

delete:
  tags:
    - config
  description: "Delete a Nostr Relay"
  responses:
    '204':
      description: "Nostr Relay Deleted"
      content:
        application/json:
          schema:
            type: object
    '400':
      description: "Invalid Request Body"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-400'
    '401':
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-401'
    '404':
      description: "Nostr Relay Not Found"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-404'
    '500':
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: '../../../../components/schemas/errors.yaml#/error-500'