openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API for testing purposes.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /pets:
    get:
      summary: Get a list of pets
      description: Returns a list of pets from the database.
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
  /pets/{petId}:
    get:
      summary: Get a single pet by ID
      description: Returns a single pet from the database.
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: A single pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the pet
        name:
          type: string
          description: The name of the pet
        tag:
          type: string
          description: A tag associated with the pet
      required:
        - id
        - name
