openapi: 3.0.0
info:
  title: SecHack365
  version: 0.1.0
paths:

  /api/v1/auth/register:
    $ref: ./paths/api/v1/auth/register.yaml
  /api/v1/auth/login:
    $ref: ./paths/api/v1/auth/login.yaml
  /api/v1/auth/logout:
    $ref: ./paths/api/v1/auth/logout.yaml

  /api/v1/users:
    $ref: ./paths/api/v1/users/all.yaml
  /api/v1/users/{id}:
    $ref: ./paths/api/v1/users/id.yaml
  /api/v1/users/me:
    $ref: ./paths/api/v1/users/me.yaml
  /api/v1/users/{id}/posts:
    $ref: ./paths/api/v1/users/posts.yaml
  /api/v1/users/{id}/follows:
    $ref: ./paths/api/v1/users/follows.yaml
  /api/v1/users/{id}/followers:
    $ref: ./paths/api/v1/users/followers.yaml
  /api/v1/users/{id}/inbox:
    $ref: ./paths/api/v1/users/inbox.yaml

  /api/v1/lookup/{username}:
    $ref: ./paths/api/v1/lookup/{username}.yaml
  
  /api/v1/follows:
    $ref: ./paths/api/v1/follows/follow.yaml
  /api/v1/follows/following/{id}:
    $ref: ./paths/api/v1/follows/following.yaml

  /api/v1/posts:
    $ref: ./paths/api/v1/posts/new.yaml
  /api/v1/posts/{id}:
    $ref: ./paths/api/v1/posts/id.yaml
  /api/v1/timeline:
    $ref: ./paths/api/v1/posts/timeline.yaml

  /api/v1/reactions:
    $ref: ./paths/api/v1/reactions/new.yaml
  
  /api/v1/configs/nostr-relay:
    $ref: ./paths/api/v1/configs/nostr-relay.yaml

  /api/v1/nodeinfo/2.0:
    $ref: ./paths/api/v1/nodeinfo/2.0.yaml
  
  /.well-known/nodeinfo:
    $ref: ./paths/.well-known/nodeinfo.yaml
  /.well-known/webfinger:
    $ref: ./paths/.well-known/webfinger.yaml
  /.well-known/nostr.json:
    $ref: ./paths/.well-known/nip05.yaml

  /api/v1/dev/mock:
    $ref: ./paths/api/v1/dev/mock.yaml
  /api/v1/dev/reset:
    $ref: ./paths/api/v1/dev/reset.yaml