openapi: 3.0.0
info:
  title: SecHack365
  version: 0.1.0
paths:

  /api/v1/users/{id}:
    $ref: ./paths/api/v1/users/{id}.yaml

  /api/v1/nodeinfo/2.0:
    $ref: ./paths/api/v1/nodeinfo/2.0.yaml
  
  /.well-known/nodeinfo:
    $ref: ./paths/.well-known/nodeinfo.yaml
  /.well-known/webfinger:
    $ref: ./paths/.well-known/webfinger.yaml
