openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/v1/nodeinfo/2.0:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  openRegistrations:
                    type: boolean
                  protocols:
                    type: array
                    items:
                      type: string
                  software:
                    type: object
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                  usage:
                    type: object
                    properties:
                      users:
                        type: object
                        properties:
                          total:
                            type: integer
                  services:
                    type: object
                    properties:
                      inbound:
                        type: object
                      outbound:
                        type: object
                  metadata:
                    type: object
                  version:
                    type: string
