#!/bin/bash

set -e

DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USER=${DB_USER}
DB_NAME=${DB_NAME}
DB_PASSWORD=${DB_PASSWORD}
export PGPASSWORD=$DB_PASSWORD

MINIO_HOST=${MINIO_HOST}
MINIO_PORT=${MINIO_PORT}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_ALIAS="myminio"
MINIO_BUCKET="static"
mc alias set $MINIO_ALIAS http://$MINIO_HOST:$MINIO_PORT $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD

BACKUP_DIR=/tmp/backups
mkdir -p $BACKUP_DIR

DATE=$(date +\%Y-\%m-\%d_\%H-\%M-\%S)
BACKUP_NAME=backup_$DATE.dump

echo "Backup started at $DATE"
pg_dump -h $DB_HOST -p $DB_PORT -U $DB_USER -F c $DB_NAME > $BACKUP_DIR/$BACKUP_NAME
mc cp $BACKUP_DIR/$BACKUP_NAME $MINIO_ALIAS/$MINIO_BUCKET/$BACKUP_NAME
echo "Backup finished: $MINIO_BUCKET/$BACKUP_NAME"
