wellknown-nodeinfo:
  type: object
  properties:
    links:
      type: array
      items:
        $ref: '#/wellknown-nodeinfo-link'
  required:
    - links

wellknown-nodeinfo-link:
  type: object
  properties:
    rel:
      type: string
      example: 'http://nodeinfo.diaspora.software/ns/schema/2.0'
    href:
      type: string
      example: 'https://localhost/api/v1/nodeinfo/2.0'
  required:
    - rel
    - href

wellknown-webfinger:
  type: object
  properties:
    subject:
      type: string
      example: 'acct:mock@localhost'
    links:
      type: array
      items:
        $ref: '#/wellknown-webfinger-link'
  required:
    - subject
    - links

wellknown-webfinger-link:
  type: object
  properties:
    rel:
      type: string
      example: 'self'
    type:
      type: string
      example: 'application/activity+json'
    href:
      type: string
      example: 'https:/localhost/api/v1/users/1'
  required:
    - rel
    - type
    - href
