/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { ActorContext } from "./actorContext";
import type { ActorIcon } from "./actorIcon";
import type { ActorPublicKey } from "./actorPublicKey";

export interface Actor {
	"@context": ActorContext;
	icon: ActorIcon;
	id: string;
	inbox: string;
	name: string;
	outbox: string;
	preferredUsername: string;
	publicKey: ActorPublicKey;
	summary: string;
	type: string;
}
