/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { SimpleUser } from "./simpleUser";

export interface Article {
	content: string;
	created_at: string;
	id: string;
	title: string;
	updated_at: string;
	user: SimpleUser;
}
