/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */

export interface Follow {
	created_at: string;
	follower_id: string;
	id: string;
	target_id: string;
	updated_at: string;
}
