/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { ApIdentifier } from "./apIdentifier";
import type { NostrIdentifier } from "./nostrIdentifier";

export interface Identifiers {
	activitypub?: ApIdentifier;
	nostr?: NostrIdentifier;
}
