/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */

export type IdentifiersActivitypub = {
	host?: string;
	local_username?: string;
	public_key?: string;
};
