/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { IdentifiersActivitypub } from "./identifiersActivitypub";
import type { IdentifiersNostr } from "./identifiersNostr";

export interface Identifiers {
	activitypub?: IdentifiersActivitypub;
	nostr?: IdentifiersNostr;
}
