/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { NodeinfoServiceInbound } from "./nodeinfoServiceInbound";
import type { NodeinfoServiceOutbound } from "./nodeinfoServiceOutbound";

export interface NodeinfoService {
	inbound: NodeinfoServiceInbound;
	outbound: NodeinfoServiceOutbound;
}
