/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { NodeinfoMetadata } from "./nodeinfoMetadata";
import type { NodeinfoService } from "./nodeinfoService";
import type { NodeinfoSoftware } from "./nodeinfoSoftware";
import type { NodeinfoUsage } from "./nodeinfoUsage";

export interface Nodeinfo {
	metadata: NodeinfoMetadata;
	openRegistrations: boolean;
	protocols: string[];
	services: NodeinfoService;
	software: NodeinfoSoftware;
	usage: NodeinfoUsage;
	version: string;
}
