/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { User } from "./user";

export interface Post {
	created_at: string;
	id: string;
	text: string;
	updated_at: string;
	user: User;
}
