/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { PostUser } from "./postUser";

export interface Post {
	content: string;
	created_at: string;
	id: string;
	like_count?: number;
	updated_at: string;
	user: PostUser;
}
