/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */

export interface PostUser {
	display_name: string;
	icon: string;
	protocol: string;
	username: string;
}
