/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */

export interface User {
	created_at: string;
	display_name: string;
	host: string;
	icon: string;
	id: string;
	profile: string;
	protocol: string;
	updated_at: string;
	username: string;
}
