/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { Identifiers } from "./identifiers";

export interface User {
	created_at: string;
	display_name: string;
	"follow-count": number;
	"follower-count": number;
	icon: string;
	id: string;
	identifiers: Identifiers;
	"post-count": number;
	profile: string;
	protocol: string;
	updated_at: string;
	username: string;
}
