/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { UserIdentifiersActivitypub } from "./userIdentifiersActivitypub";
import type { UserIdentifiersNostr } from "./userIdentifiersNostr";

export type UserIdentifiers = {
	activitypub?: UserIdentifiersActivitypub;
	nostr?: UserIdentifiersNostr;
};
