/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import type { WellknownWebfingerLink } from "./wellknownWebfingerLink";

export interface WellknownWebfinger {
	links: WellknownWebfingerLink[];
	subject: string;
}
