DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ap_user_identifiers CASCADE;
DROP TABLE IF EXISTS nostr_user_identifiers CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

DROP TYPE IF EXISTS protocol;
