DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ap_user_identifiers CASCADE;
DROP TABLE IF EXISTS nostr_user_identifiers CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS article_comments CASCADE;
DROP TABLE IF EXISTS reactions CASCADE;
DROP TABLE IF EXISTS nostr_relays CASCADE;

DROP TYPE IF EXISTS protocol;
