/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SecHack365
 * OpenAPI spec version: 0.1.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";
import type {
	Actor,
	Auth,
	DeleteApiV1ConfigsNostrRelay204,
	DeleteApiV1Follows204,
	DeleteApiV1PostsId204,
	DeleteApiV1Reactions204,
	Error400,
	Error401,
	Error404,
	Error409,
	Error500,
	Found,
	GetApiV1DevMock201,
	GetApiV1DevMock404,
	GetApiV1DevMock500,
	GetApiV1DevReset204,
	GetApiV1DevReset404,
	GetApiV1DevReset500,
	GetApiV1TimelineParams,
	GetApiV1UsersIdPostsParams,
	GetWellKnownWebfingerParams,
	NewReaction,
	Newfollow,
	Newpost,
	Nodeinfo,
	NostrRelay,
	Post,
	PostApiV1AuthLogin204,
	PostApiV1AuthLogout204,
	PostApiV1AuthRegister201,
	PostApiV1ConfigsNostrRelay201,
	PostApiV1Follows201,
	PostApiV1Posts201,
	PostApiV1Reactions201,
	SimpleUser,
	User,
	WellknownNodeinfo,
	WellknownWebfinger,
} from "./schemas";

/**
 * Create User
 */
export const postApiV1AuthRegister = (
	auth: Auth,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1AuthRegister201>> => {
	return axios.post("/api/v1/auth/register", auth, options);
};

export const getPostApiV1AuthRegisterMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: Auth },
	): Promise<AxiosResponse<PostApiV1AuthRegister201>> => {
		return postApiV1AuthRegister(arg, options);
	};
};
export const getPostApiV1AuthRegisterMutationKey = () =>
	["/api/v1/auth/register"] as const;

export type PostApiV1AuthRegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1AuthRegister>>
>;
export type PostApiV1AuthRegisterMutationError = AxiosError<
	Error400 | Error409 | Error500
>;

export const usePostApiV1AuthRegister = <
	TError = AxiosError<Error400 | Error409 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1AuthRegister>>,
		TError,
		Key,
		Auth,
		Awaited<ReturnType<typeof postApiV1AuthRegister>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiV1AuthRegisterMutationKey();
	const swrFn = getPostApiV1AuthRegisterMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Login
 */
export const postApiV1AuthLogin = (
	auth: Auth,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1AuthLogin204>> => {
	return axios.post("/api/v1/auth/login", auth, options);
};

export const getPostApiV1AuthLoginMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: Auth },
	): Promise<AxiosResponse<PostApiV1AuthLogin204>> => {
		return postApiV1AuthLogin(arg, options);
	};
};
export const getPostApiV1AuthLoginMutationKey = () =>
	["/api/v1/auth/login"] as const;

export type PostApiV1AuthLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1AuthLogin>>
>;
export type PostApiV1AuthLoginMutationError = AxiosError<
	Error400 | Error401 | Error500
>;

export const usePostApiV1AuthLogin = <
	TError = AxiosError<Error400 | Error401 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1AuthLogin>>,
		TError,
		Key,
		Auth,
		Awaited<ReturnType<typeof postApiV1AuthLogin>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiV1AuthLoginMutationKey();
	const swrFn = getPostApiV1AuthLoginMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Logout
 */
export const postApiV1AuthLogout = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1AuthLogout204>> => {
	return axios.post("/api/v1/auth/logout", undefined, options);
};

export const getPostApiV1AuthLogoutMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		__: { arg: Arguments },
	): Promise<AxiosResponse<PostApiV1AuthLogout204>> => {
		return postApiV1AuthLogout(options);
	};
};
export const getPostApiV1AuthLogoutMutationKey = () =>
	["/api/v1/auth/logout"] as const;

export type PostApiV1AuthLogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1AuthLogout>>
>;
export type PostApiV1AuthLogoutMutationError = AxiosError<unknown>;

export const usePostApiV1AuthLogout = <TError = AxiosError<unknown>>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1AuthLogout>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof postApiV1AuthLogout>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiV1AuthLogoutMutationKey();
	const swrFn = getPostApiV1AuthLogoutMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get All Users (for debug)
 */
export const getApiV1Users = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<User[]>> => {
	return axios.get("/api/v1/users", options);
};

export const getGetApiV1UsersKey = () => ["/api/v1/users"] as const;

export type GetApiV1UsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Users>>
>;
export type GetApiV1UsersQueryError = AxiosError<Error500>;

export const useGetApiV1Users = <TError = AxiosError<Error500>>(options?: {
	swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1Users>>, TError> & {
		swrKey?: Key;
		enabled?: boolean;
	};
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1UsersKey() : null));
	const swrFn = () => getApiV1Users(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get User by ID
 */
export const getApiV1UsersId = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<User | Actor>> => {
	return axios.get(`/api/v1/users/${id}`, options);
};

export const getGetApiV1UsersIdKey = (id: string) =>
	[`/api/v1/users/${id}`] as const;

export type GetApiV1UsersIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1UsersId>>
>;
export type GetApiV1UsersIdQueryError = AxiosError<
	Error400 | Error404 | Error500
>;

export const useGetApiV1UsersId = <
	TError = AxiosError<Error400 | Error404 | Error500>,
>(
	id: string,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1UsersId>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!id;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1UsersIdKey(id) : null));
	const swrFn = () => getApiV1UsersId(id, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Current User
 */
export const getApiV1UsersMe = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<User>> => {
	return axios.get("/api/v1/users/me", options);
};

export const getGetApiV1UsersMeKey = () => ["/api/v1/users/me"] as const;

export type GetApiV1UsersMeQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1UsersMe>>
>;
export type GetApiV1UsersMeQueryError = AxiosError<Error404 | Error500>;

export const useGetApiV1UsersMe = <
	TError = AxiosError<Error404 | Error500>,
>(options?: {
	swr?: SWRConfiguration<
		Awaited<ReturnType<typeof getApiV1UsersMe>>,
		TError
	> & { swrKey?: Key; enabled?: boolean };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1UsersMeKey() : null));
	const swrFn = () => getApiV1UsersMe(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Latest Posts of User
 */
export const getApiV1UsersIdPosts = (
	id: string,
	params?: GetApiV1UsersIdPostsParams,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<Post[]>> => {
	return axios.get(`/api/v1/users/${id}/posts`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetApiV1UsersIdPostsKey = (
	id: string,
	params?: GetApiV1UsersIdPostsParams,
) => [`/api/v1/users/${id}/posts`, ...(params ? [params] : [])] as const;

export type GetApiV1UsersIdPostsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1UsersIdPosts>>
>;
export type GetApiV1UsersIdPostsQueryError = AxiosError<
	Error400 | Error404 | Error500
>;

export const useGetApiV1UsersIdPosts = <
	TError = AxiosError<Error400 | Error404 | Error500>,
>(
	id: string,
	params?: GetApiV1UsersIdPostsParams,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1UsersIdPosts>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!id;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1UsersIdPostsKey(id, params) : null));
	const swrFn = () => getApiV1UsersIdPosts(id, params, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Follows of User
 */
export const getApiV1UsersIdFollows = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<SimpleUser[]>> => {
	return axios.get(`/api/v1/users/${id}/follows`, options);
};

export const getGetApiV1UsersIdFollowsKey = (id: string) =>
	[`/api/v1/users/${id}/follows`] as const;

export type GetApiV1UsersIdFollowsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1UsersIdFollows>>
>;
export type GetApiV1UsersIdFollowsQueryError = AxiosError<Error400 | Error500>;

export const useGetApiV1UsersIdFollows = <
	TError = AxiosError<Error400 | Error500>,
>(
	id: string,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1UsersIdFollows>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!id;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1UsersIdFollowsKey(id) : null));
	const swrFn = () => getApiV1UsersIdFollows(id, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Followers of User
 */
export const getApiV1UsersIdFollowers = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<SimpleUser[]>> => {
	return axios.get(`/api/v1/users/${id}/followers`, options);
};

export const getGetApiV1UsersIdFollowersKey = (id: string) =>
	[`/api/v1/users/${id}/followers`] as const;

export type GetApiV1UsersIdFollowersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1UsersIdFollowers>>
>;
export type GetApiV1UsersIdFollowersQueryError = AxiosError<
	Error400 | Error500
>;

export const useGetApiV1UsersIdFollowers = <
	TError = AxiosError<Error400 | Error500>,
>(
	id: string,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1UsersIdFollowers>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!id;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1UsersIdFollowersKey(id) : null));
	const swrFn = () => getApiV1UsersIdFollowers(id, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Lookup (Remote/Local) User
 */
export const getApiV1LookupUsername = (
	username: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<User>> => {
	return axios.get(`/api/v1/lookup/${username}`, options);
};

export const getGetApiV1LookupUsernameKey = (username: string) =>
	[`/api/v1/lookup/${username}`] as const;

export type GetApiV1LookupUsernameQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1LookupUsername>>
>;
export type GetApiV1LookupUsernameQueryError = AxiosError<
	Error400 | Error404 | Error500
>;

export const useGetApiV1LookupUsername = <
	TError = AxiosError<Error400 | Error404 | Error500>,
>(
	username: string,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1LookupUsername>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!username;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1LookupUsernameKey(username) : null));
	const swrFn = () => getApiV1LookupUsername(username, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Follow
 */
export const postApiV1Follows = (
	newfollow: Newfollow,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1Follows201>> => {
	return axios.post("/api/v1/follows", newfollow, options);
};

export const getPostApiV1FollowsMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: Newfollow },
	): Promise<AxiosResponse<PostApiV1Follows201>> => {
		return postApiV1Follows(arg, options);
	};
};
export const getPostApiV1FollowsMutationKey = () =>
	["/api/v1/follows"] as const;

export type PostApiV1FollowsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1Follows>>
>;
export type PostApiV1FollowsMutationError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const usePostApiV1Follows = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1Follows>>,
		TError,
		Key,
		Newfollow,
		Awaited<ReturnType<typeof postApiV1Follows>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiV1FollowsMutationKey();
	const swrFn = getPostApiV1FollowsMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Unfollow
 */
export const deleteApiV1Follows = (
	newfollow: Newfollow,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeleteApiV1Follows204>> => {
	return axios.delete("/api/v1/follows", { data: newfollow, ...options });
};

export const getDeleteApiV1FollowsMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: Newfollow },
	): Promise<AxiosResponse<DeleteApiV1Follows204>> => {
		return deleteApiV1Follows(arg, options);
	};
};
export const getDeleteApiV1FollowsMutationKey = () =>
	["/api/v1/follows"] as const;

export type DeleteApiV1FollowsMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiV1Follows>>
>;
export type DeleteApiV1FollowsMutationError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const useDeleteApiV1Follows = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof deleteApiV1Follows>>,
		TError,
		Key,
		Newfollow,
		Awaited<ReturnType<typeof deleteApiV1Follows>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getDeleteApiV1FollowsMutationKey();
	const swrFn = getDeleteApiV1FollowsMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Check if User is Following
 */
export const getApiV1FollowsFollowingId = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<Found>> => {
	return axios.get(`/api/v1/follows/following/${id}`, options);
};

export const getGetApiV1FollowsFollowingIdKey = (id: string) =>
	[`/api/v1/follows/following/${id}`] as const;

export type GetApiV1FollowsFollowingIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1FollowsFollowingId>>
>;
export type GetApiV1FollowsFollowingIdQueryError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const useGetApiV1FollowsFollowingId = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(
	id: string,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1FollowsFollowingId>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!id;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1FollowsFollowingIdKey(id) : null));
	const swrFn = () => getApiV1FollowsFollowingId(id, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Create Post
 */
export const postApiV1Posts = (
	newpost: Newpost,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1Posts201>> => {
	return axios.post("/api/v1/posts", newpost, options);
};

export const getPostApiV1PostsMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: Newpost },
	): Promise<AxiosResponse<PostApiV1Posts201>> => {
		return postApiV1Posts(arg, options);
	};
};
export const getPostApiV1PostsMutationKey = () => ["/api/v1/posts"] as const;

export type PostApiV1PostsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1Posts>>
>;
export type PostApiV1PostsMutationError = AxiosError<
	Error400 | Error401 | Error500
>;

export const usePostApiV1Posts = <
	TError = AxiosError<Error400 | Error401 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1Posts>>,
		TError,
		Key,
		Newpost,
		Awaited<ReturnType<typeof postApiV1Posts>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiV1PostsMutationKey();
	const swrFn = getPostApiV1PostsMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Post by ID
 */
export const getApiV1PostsId = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<Post>> => {
	return axios.get(`/api/v1/posts/${id}`, options);
};

export const getGetApiV1PostsIdKey = (id: string) =>
	[`/api/v1/posts/${id}`] as const;

export type GetApiV1PostsIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1PostsId>>
>;
export type GetApiV1PostsIdQueryError = AxiosError<
	Error400 | Error404 | Error500
>;

export const useGetApiV1PostsId = <
	TError = AxiosError<Error400 | Error404 | Error500>,
>(
	id: string,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1PostsId>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!id;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1PostsIdKey(id) : null));
	const swrFn = () => getApiV1PostsId(id, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Delete Post by ID
 */
export const deleteApiV1PostsId = (
	id: string,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeleteApiV1PostsId204>> => {
	return axios.delete(`/api/v1/posts/${id}`, options);
};

export const getDeleteApiV1PostsIdMutationFetcher = (
	id: string,
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		__: { arg: Arguments },
	): Promise<AxiosResponse<DeleteApiV1PostsId204>> => {
		return deleteApiV1PostsId(id, options);
	};
};
export const getDeleteApiV1PostsIdMutationKey = (id: string) =>
	[`/api/v1/posts/${id}`] as const;

export type DeleteApiV1PostsIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiV1PostsId>>
>;
export type DeleteApiV1PostsIdMutationError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const useDeleteApiV1PostsId = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(
	id: string,
	options?: {
		swr?: SWRMutationConfiguration<
			Awaited<ReturnType<typeof deleteApiV1PostsId>>,
			TError,
			Key,
			Arguments,
			Awaited<ReturnType<typeof deleteApiV1PostsId>>
		> & { swrKey?: string };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getDeleteApiV1PostsIdMutationKey(id);
	const swrFn = getDeleteApiV1PostsIdMutationFetcher(id, axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Timeline
 */
export const getApiV1Timeline = (
	params?: GetApiV1TimelineParams,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<Post[]>> => {
	return axios.get("/api/v1/timeline", {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetApiV1TimelineKey = (params?: GetApiV1TimelineParams) =>
	["/api/v1/timeline", ...(params ? [params] : [])] as const;

export type GetApiV1TimelineQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Timeline>>
>;
export type GetApiV1TimelineQueryError = AxiosError<Error500>;

export const useGetApiV1Timeline = <TError = AxiosError<Error500>>(
	params?: GetApiV1TimelineParams,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1Timeline>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1TimelineKey(params) : null));
	const swrFn = () => getApiV1Timeline(params, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Add Reaction to Post
 */
export const postApiV1Reactions = (
	newReaction: NewReaction,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1Reactions201>> => {
	return axios.post("/api/v1/reactions", newReaction, options);
};

export const getPostApiV1ReactionsMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: NewReaction },
	): Promise<AxiosResponse<PostApiV1Reactions201>> => {
		return postApiV1Reactions(arg, options);
	};
};
export const getPostApiV1ReactionsMutationKey = () =>
	["/api/v1/reactions"] as const;

export type PostApiV1ReactionsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1Reactions>>
>;
export type PostApiV1ReactionsMutationError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const usePostApiV1Reactions = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1Reactions>>,
		TError,
		Key,
		NewReaction,
		Awaited<ReturnType<typeof postApiV1Reactions>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiV1ReactionsMutationKey();
	const swrFn = getPostApiV1ReactionsMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Remove Reaction to Post
 */
export const deleteApiV1Reactions = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeleteApiV1Reactions204>> => {
	return axios.delete("/api/v1/reactions", options);
};

export const getDeleteApiV1ReactionsMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		__: { arg: Arguments },
	): Promise<AxiosResponse<DeleteApiV1Reactions204>> => {
		return deleteApiV1Reactions(options);
	};
};
export const getDeleteApiV1ReactionsMutationKey = () =>
	["/api/v1/reactions"] as const;

export type DeleteApiV1ReactionsMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiV1Reactions>>
>;
export type DeleteApiV1ReactionsMutationError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const useDeleteApiV1Reactions = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof deleteApiV1Reactions>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof deleteApiV1Reactions>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getDeleteApiV1ReactionsMutationKey();
	const swrFn = getDeleteApiV1ReactionsMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Register a New Nostr Relay
 */
export const postApiV1ConfigsNostrRelay = (
	nostrRelay: NostrRelay,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiV1ConfigsNostrRelay201>> => {
	return axios.post("/api/v1/configs/nostr-relay", nostrRelay, options);
};

export const getPostApiV1ConfigsNostrRelayMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		{ arg }: { arg: NostrRelay },
	): Promise<AxiosResponse<PostApiV1ConfigsNostrRelay201>> => {
		return postApiV1ConfigsNostrRelay(arg, options);
	};
};
export const getPostApiV1ConfigsNostrRelayMutationKey = () =>
	["/api/v1/configs/nostr-relay"] as const;

export type PostApiV1ConfigsNostrRelayMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1ConfigsNostrRelay>>
>;
export type PostApiV1ConfigsNostrRelayMutationError = AxiosError<
	Error400 | Error401 | Error500
>;

export const usePostApiV1ConfigsNostrRelay = <
	TError = AxiosError<Error400 | Error401 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiV1ConfigsNostrRelay>>,
		TError,
		Key,
		NostrRelay,
		Awaited<ReturnType<typeof postApiV1ConfigsNostrRelay>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey =
		swrOptions?.swrKey ?? getPostApiV1ConfigsNostrRelayMutationKey();
	const swrFn = getPostApiV1ConfigsNostrRelayMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * Get Nostr Relays List
 */
export const getApiV1ConfigsNostrRelay = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<NostrRelay[]>> => {
	return axios.get("/api/v1/configs/nostr-relay", options);
};

export const getGetApiV1ConfigsNostrRelayKey = () =>
	["/api/v1/configs/nostr-relay"] as const;

export type GetApiV1ConfigsNostrRelayQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1ConfigsNostrRelay>>
>;
export type GetApiV1ConfigsNostrRelayQueryError = AxiosError<
	Error401 | Error500
>;

export const useGetApiV1ConfigsNostrRelay = <
	TError = AxiosError<Error401 | Error500>,
>(options?: {
	swr?: SWRConfiguration<
		Awaited<ReturnType<typeof getApiV1ConfigsNostrRelay>>,
		TError
	> & { swrKey?: Key; enabled?: boolean };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1ConfigsNostrRelayKey() : null));
	const swrFn = () => getApiV1ConfigsNostrRelay(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Delete a Nostr Relay
 */
export const deleteApiV1ConfigsNostrRelay = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeleteApiV1ConfigsNostrRelay204>> => {
	return axios.delete("/api/v1/configs/nostr-relay", options);
};

export const getDeleteApiV1ConfigsNostrRelayMutationFetcher = (
	options?: AxiosRequestConfig,
) => {
	return (
		_: Key,
		__: { arg: Arguments },
	): Promise<AxiosResponse<DeleteApiV1ConfigsNostrRelay204>> => {
		return deleteApiV1ConfigsNostrRelay(options);
	};
};
export const getDeleteApiV1ConfigsNostrRelayMutationKey = () =>
	["/api/v1/configs/nostr-relay"] as const;

export type DeleteApiV1ConfigsNostrRelayMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiV1ConfigsNostrRelay>>
>;
export type DeleteApiV1ConfigsNostrRelayMutationError = AxiosError<
	Error400 | Error401 | Error404 | Error500
>;

export const useDeleteApiV1ConfigsNostrRelay = <
	TError = AxiosError<Error400 | Error401 | Error404 | Error500>,
>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof deleteApiV1ConfigsNostrRelay>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof deleteApiV1ConfigsNostrRelay>>
	> & { swrKey?: string };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const swrKey =
		swrOptions?.swrKey ?? getDeleteApiV1ConfigsNostrRelayMutationKey();
	const swrFn = getDeleteApiV1ConfigsNostrRelayMutationFetcher(axiosOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};

/**
 * NodeInfo 2.0
 */
export const getApiV1Nodeinfo20 = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<Nodeinfo>> => {
	return axios.get("/api/v1/nodeinfo/2.0", options);
};

export const getGetApiV1Nodeinfo20Key = () => ["/api/v1/nodeinfo/2.0"] as const;

export type GetApiV1Nodeinfo20QueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Nodeinfo20>>
>;
export type GetApiV1Nodeinfo20QueryError = AxiosError<Error500>;

export const useGetApiV1Nodeinfo20 = <TError = AxiosError<Error500>>(options?: {
	swr?: SWRConfiguration<
		Awaited<ReturnType<typeof getApiV1Nodeinfo20>>,
		TError
	> & { swrKey?: Key; enabled?: boolean };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1Nodeinfo20Key() : null));
	const swrFn = () => getApiV1Nodeinfo20(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * NodeInfo
 */
export const getWellKnownNodeinfo = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<WellknownNodeinfo>> => {
	return axios.get("/.well-known/nodeinfo", options);
};

export const getGetWellKnownNodeinfoKey = () =>
	["/.well-known/nodeinfo"] as const;

export type GetWellKnownNodeinfoQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWellKnownNodeinfo>>
>;
export type GetWellKnownNodeinfoQueryError = AxiosError<unknown>;

export const useGetWellKnownNodeinfo = <
	TError = AxiosError<unknown>,
>(options?: {
	swr?: SWRConfiguration<
		Awaited<ReturnType<typeof getWellKnownNodeinfo>>,
		TError
	> & { swrKey?: Key; enabled?: boolean };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetWellKnownNodeinfoKey() : null));
	const swrFn = () => getWellKnownNodeinfo(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * WebFinger
 */
export const getWellKnownWebfinger = (
	params: GetWellKnownWebfingerParams,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<WellknownWebfinger>> => {
	return axios.get("/.well-known/webfinger", {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetWellKnownWebfingerKey = (
	params: GetWellKnownWebfingerParams,
) => ["/.well-known/webfinger", ...(params ? [params] : [])] as const;

export type GetWellKnownWebfingerQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWellKnownWebfinger>>
>;
export type GetWellKnownWebfingerQueryError = AxiosError<
	Error400 | Error404 | Error500
>;

export const useGetWellKnownWebfinger = <
	TError = AxiosError<Error400 | Error404 | Error500>,
>(
	params: GetWellKnownWebfingerParams,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getWellKnownWebfinger>>,
			TError
		> & { swrKey?: Key; enabled?: boolean };
		axios?: AxiosRequestConfig;
	},
) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetWellKnownWebfingerKey(params) : null));
	const swrFn = () => getWellKnownWebfinger(params, axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Generate Mock
 */
export const getApiV1DevMock = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiV1DevMock201>> => {
	return axios.get("/api/v1/dev/mock", options);
};

export const getGetApiV1DevMockKey = () => ["/api/v1/dev/mock"] as const;

export type GetApiV1DevMockQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1DevMock>>
>;
export type GetApiV1DevMockQueryError = AxiosError<
	GetApiV1DevMock404 | GetApiV1DevMock500
>;

export const useGetApiV1DevMock = <
	TError = AxiosError<GetApiV1DevMock404 | GetApiV1DevMock500>,
>(options?: {
	swr?: SWRConfiguration<
		Awaited<ReturnType<typeof getApiV1DevMock>>,
		TError
	> & { swrKey?: Key; enabled?: boolean };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1DevMockKey() : null));
	const swrFn = () => getApiV1DevMock(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};

/**
 * Reset Database
 */
export const getApiV1DevReset = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiV1DevReset204>> => {
	return axios.get("/api/v1/dev/reset", options);
};

export const getGetApiV1DevResetKey = () => ["/api/v1/dev/reset"] as const;

export type GetApiV1DevResetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1DevReset>>
>;
export type GetApiV1DevResetQueryError = AxiosError<
	GetApiV1DevReset404 | GetApiV1DevReset500
>;

export const useGetApiV1DevReset = <
	TError = AxiosError<GetApiV1DevReset404 | GetApiV1DevReset500>,
>(options?: {
	swr?: SWRConfiguration<
		Awaited<ReturnType<typeof getApiV1DevReset>>,
		TError
	> & { swrKey?: Key; enabled?: boolean };
	axios?: AxiosRequestConfig;
}) => {
	const { swr: swrOptions, axios: axiosOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1DevResetKey() : null));
	const swrFn = () => getApiV1DevReset(axiosOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};
