FROM golang:1.24-alpine AS build
ENV TZ=Asia/Tokyo

WORKDIR /opt/app

COPY go.mod .
COPY go.sum .
RUN go mod tidy

COPY . .
RUN go build -o /bin/server ./cmd/server


FROM gcr.io/distroless/base:nonroot AS runner
ENV TZ=Asia/Tokyo
ENV GOENV=production

EXPOSE ${PORT}

COPY --from=build /bin/server /bin/server

USER nonroot
ENTRYPOINT ["/bin/server"]
