FROM golang:1.22-alpine
ENV TZ=Asia/Tokyo

WORKDIR /opt/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build -o /bin/server ./cmd/server

EXPOSE ${PORT}
ENTRYPOINT ["/bin/server"]
