FROM golang:1.23-alpine
ENV TZ=Asia/Tokyo

WORKDIR /opt/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go install github.com/air-verse/air@latest

EXPOSE ${PORT}
CMD ["air", "-c", ".air.toml"]
