name: openapi-ci
on:
  push:
    paths:
      - 'openapi/**'
      - '.github/workflows/openapi-ci.yaml'

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: OpenAPI check
        run: |
          make openapi
          git diff -- api/pkg/openapi/types.gen.go --exit-code
